services:
  server:
    image: "mailculators-${IMAGE_SUFFIX}"
    environment:
      APP_DATA_PATH: "/var/lib/mailculator-server"
      INPUT_PATH: "/input"
      OUTBOX_PATH: "/maildir/outbox"
    volumes:
      - ./data/input:/var/lib/mailculator-server/input
      - ./data/maildir:/var/lib/mailculator-server/maildir
    ports:
      - "127.0.0.1:8101:8080"
    networks:
      - mailculator-network

  processor:
    image: "mailculatorp-${IMAGE_SUFFIX}"
    environment:
      ENV: "DEV"
      APP_DATA_PATH: "/var/lib/mailculator-processor/maildir"
      OUTBOX_PATH: "/outbox"
      CHECK_INTERVAL: 6
      LAST_MOD_INTERVAL: 15
      EMPTY_DIR_INTERVAL: 120
      AWS_ACCESS_KEY_ID: "your-access-key-id"
      AWS_SECRET_ACCESS_KEY: "your-secret-access-key"
      AWS_REGION: "your-region"
    volumes:
      - ./data/maildir:/var/lib/mailculator-processor/maildir
    ports:
      - "127.0.0.1:9091:9090"
    networks:
      - mailculator-network

  filebrowser:
    image: "mailculatorf-${IMAGE_SUFFIX}"
    volumes:
      - ./data/maildir:/srv/maildir
    ports:
      - "127.0.0.1:8102:80"
    networks:
      - mailculator-network

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - mailculator-network

  localstack:
    image: "localstack/localstack:latest"
    environment:
      - SERVICES=ses
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data/localstack:/tmp/localstack"
    ports:
      - "127.0.0.1:4566:4566"  # LocalStack main service port
    networks:
      - mailculator-network

networks:
  mailculator-network:
    driver: bridge
